# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 7.2.2"
gem "puma", "~> 6.0"
gem "sqlite3"
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "lookbook"

gem "educhain_view_components", path: "../"

group :development, :test do
  gem "foreman"
  gem "byebug"
end

group :development do
  gem "listen"
  gem "web-console", ">= 4.1.0"
end
